function textHealth(content) 
    SetTextFont(1)
    SetTextProportional(0)
    SetTextScale(0.5,0.5)
    SetTextEntry("STRING")
    AddTextComponentString("Health: " ..content.."%")
    DrawText(0.88,0.62)
end
function textStamina(content) 
    SetTextFont(1)
    SetTextProportional(0)
    SetTextScale(0.5,0.5)
    SetTextEntry("STRING")
    AddTextComponentString("Stamina: " ..content.."%")
    DrawText(0.88,0.77)
end
function textMoney(content) 
    SetTextFont(1)
    SetTextProportional(0)
    SetTextScale(0.5,0.5)
    SetTextEntry("STRING")
    AddTextComponentString("Cash: $" ..content)
    DrawText(0.88,0.80)
end
function textBank(content) 
    SetTextFont(1)
    SetTextProportional(0)
    SetTextScale(0.5,0.5)
    SetTextEntry("STRING")
    AddTextComponentString("Bank: $" ..content)
    DrawText(0.88,0.83)
end
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(2)
        local Health = (GetEntityHealth(GetPlayerPed(-1)) - 100)
        textHealth(math.floor(Health))
        textStamina(math.floor(GetPlayerSprintStaminaRemaining(GetPlayerPed(-1))))
        textMoney(Config.money)
        textBank(Config.bank)
    end
end)